module.exports = [{name:"100 Mph",
hexvalue:"#c93f38"},
{name:"18th Century Green",
hexvalue:"#a59344"},
{name:"1975 Earth Red",
hexvalue:"#7b463b"},
{name:"1989 Miami Hotline",
hexvalue:"#dd3366"},
{name:"20000 Leagues Under the Sea",
hexvalue:"#191970"},
{name:"24 Karat",
hexvalue:"#ab7f46"},
{name:"3AM in Shibuya",
hexvalue:"#225577"},
{name:"3am Latte",
hexvalue:"#c0a98e"},
{name:"400XT Film",
hexvalue:"#d2d2c0"},
{name:"5-Masted Preußen",
hexvalue:"#9bafad"},
{name:"8 Bit Eggplant",
hexvalue:"#990066"},
{name:"90% Cocoa",
hexvalue:"#3d1c02"},
{name:"A Brand New Day",
hexvalue:"#ffaabb"},
{name:"A Certain Shade Of Green",
hexvalue:"#d1edee"},
{name:"A Dime a Dozen",
hexvalue:"#d3dde4"},
{name:"A Hint of Incremental Blue",
hexvalue:"#456789"},
{name:"A La Mode",
hexvalue:"#f6ecde"},
{name:"A Lot of Love",
hexvalue:"#ffbcc5"},
{name:"A Pair of Brown Eyes",
hexvalue:"#bfaf92"},
{name:"A Smell of Bakery",
hexvalue:"#f3e9d9"},
{name:"A State of Mint",
hexvalue:"#88ffcc"},
{name:"Aare River",
hexvalue:"#00b89f"},
{name:"Aare River Brienz",
hexvalue:"#05a3ad"},
{name:"Aarhusian Sky",
hexvalue:"#1150af"},
{name:"Abaddon Black",
hexvalue:"#231f20"},
{name:"Abaidh White",
hexvalue:"#f2f1e6"},
{name:"Abalone",
hexvalue:"#f8f3f6"},
{name:"Abalone Shell",
hexvalue:"#e1ded9"},
{name:"Abandoned Mansion",
hexvalue:"#94877e"},
{name:"Abbey",
hexvalue:"#4c4f56"},
{name:"Abbey Road",
hexvalue:"#a79f92"},
{name:"Abbey Stone",
hexvalue:"#aba798"},
{name:"Abbey White",
hexvalue:"#ece6d0"},
{name:"Abbot",
hexvalue:"#4d3c2d"},
{name:"Abduction",
hexvalue:"#166461"},
{name:"Âbi Blue",
hexvalue:"#5ba8ff"},
{name:"Abilene Lace",
hexvalue:"#eae3d2"},
{name:"Ablaze",
hexvalue:"#c04641"},
{name:"Abomination",
hexvalue:"#77aa77"},
{name:"Abra Cadabra",
hexvalue:"#966165"},
{name:"Abra Goldenrod",
hexvalue:"#eec400"},
{name:"Absence of Light",
hexvalue:"#15151c"},
{name:"Absinthe Green",
hexvalue:"#76b583"},
{name:"Absinthe Turquoise",
hexvalue:"#008a60"},
{name:"Absolute Apricot",
hexvalue:"#ff9944"},
{name:"Absolute Zero",
hexvalue:"#0048ba"},
{name:"Abstract",
hexvalue:"#e4cb97"},
{name:"Abstract White",
hexvalue:"#ede9dd"},
{name:"Abundance",
hexvalue:"#629763"},
{name:"Abura Green",
hexvalue:"#a19361"},
{name:"Abyss",
hexvalue:"#8f9e9d"},
{name:"Abyssal Anchorfish Blue",
hexvalue:"#1b2632"},
{name:"Abyssal Blue",
hexvalue:"#00035b"},
{name:"Abyssal Depths",
hexvalue:"#10246a"},
{name:"Abyssal Waters",
hexvalue:"#005765"},
{name:"Abysse",
hexvalue:"#3d5758"},
{name:"Abyssopelagic Water",
hexvalue:"#000033"},
{name:"Acacia",
hexvalue:"#dacd65"},
{name:"Acacia Green",
hexvalue:"#486241"},
{name:"Acacia Haze",
hexvalue:"#969c92"},
{name:"Academic Blue",
hexvalue:"#2c3e56"},
{name:"Academy Purple",
hexvalue:"#525367"},
{name:"Acadia",
hexvalue:"#35312c"},
{name:"Acadia Bloom",
hexvalue:"#e5b7be"},
{name:"Acai",
hexvalue:"#46295a"},
{name:"Acai Berry",
hexvalue:"#42314b"},
{name:"Acai Juice",
hexvalue:"#942193"},
{name:"Acajou",
hexvalue:"#4c2f27"},
{name:"Acanthus",
hexvalue:"#9899a7"},
{name:"Acanthus Leaf",
hexvalue:"#90977a"},
{name:"Acapulco",
hexvalue:"#75aa94"},
{name:"Acapulco Cliffs",
hexvalue:"#4e9aa8"},
{name:"Acapulco Dive",
hexvalue:"#65a7dd"},
{name:"Acapulco Sun",
hexvalue:"#eb8a44"},
{name:"Accent Green Blue",
hexvalue:"#208468"},
{name:"Accent Orange",
hexvalue:"#e56d00"},
{name:"Accessible Beige",
hexvalue:"#d2c7b7"},
{name:"Accolade",
hexvalue:"#7c94b2"},
{name:"Accursed Black",
hexvalue:"#090807"},
{name:"Ace",
hexvalue:"#c7cce7"},
{name:"Aceituna Picante",
hexvalue:"#727a5f"},
{name:"Aceto Balsamico",
hexvalue:"#4e4f48"},
{name:"Acid",
hexvalue:"#00ff22"},
{name:"Acid Blond",
hexvalue:"#efedd7"},
{name:"Acid Candy",
hexvalue:"#a8c74d"},
{name:"Acid Drop",
hexvalue:"#11ff22"},
{name:"Acid Green",
hexvalue:"#8ffe09"},
{name:"Acid Lime",
hexvalue:"#badf30"},
{name:"Acid Pool",
hexvalue:"#00ee22"},
{name:"Acid Pops",
hexvalue:"#33ee66"},
{name:"Acid Sleazebag",
hexvalue:"#4fc172"},
{name:"Acier",
hexvalue:"#9e9991"},
{name:"Acini di Pepe",
hexvalue:"#ffd8b1"},
{name:"Acorn",
hexvalue:"#7e5e52"},
{name:"Acorn Spice",
hexvalue:"#b87439"},
{name:"Acorn Squash",
hexvalue:"#eda740"},
{name:"Acoustic White",
hexvalue:"#efece1"},
{name:"Across the Bay",
hexvalue:"#b3e1e8"},
{name:"Actinic Light",
hexvalue:"#ff44ee"},
{name:"Action Green",
hexvalue:"#00504b"},
{name:"Active Green",
hexvalue:"#00a67e"},
{name:"Active Turquoise",
hexvalue:"#006f72"},
{name:"Active Volcano",
hexvalue:"#bb1133"},
{name:"Actor's Star",
hexvalue:"#a7a6a3"},
{name:"Adamite Green",
hexvalue:"#3b845e"},
{name:"Adana Kebabı",
hexvalue:"#661111"},
{name:"Adaptive Shade",
hexvalue:"#867e70"},
{name:"Addo Skin",
hexvalue:"#585d58"},
{name:"Adeline",
hexvalue:"#ccb0b5"},
{name:"Adept",
hexvalue:"#293947"},
{name:"Adeptus Battlegrey",
hexvalue:"#7c8286"},
{name:"Adhesion",
hexvalue:"#9e9cab"},
{name:"Adirondack",
hexvalue:"#b0b9c1"},
{name:"Adirondack Blue",
hexvalue:"#74858f"},
{name:"Admiral Blue",
hexvalue:"#50647f"},
{name:"Admiralty",
hexvalue:"#404e61"},
{name:"Admiration",
hexvalue:"#f6f3d3"},
{name:"Adobe",
hexvalue:"#bd6c48"},
{name:"Adobe Avenue",
hexvalue:"#fb9587"},
{name:"Adobe Beige",
hexvalue:"#dcbfa6"},
{name:"Adobe Rose",
hexvalue:"#ba9f99"},
{name:"Adobe Sand",
hexvalue:"#e8dec5"},
{name:"Adobe South",
hexvalue:"#e5c1a7"},
{name:"Adobe Straw",
hexvalue:"#c3a998"},
{name:"Adobe White",
hexvalue:"#e6dbc4"},
{name:"Adonis",
hexvalue:"#64b5bf"},
{name:"Adonis Rose Yellow",
hexvalue:"#efbf4d"},
{name:"Adorable",
hexvalue:"#e3beb0"},
{name:"Adriatic Blue",
hexvalue:"#5c899b"},
{name:"Adriatic Haze",
hexvalue:"#96c6cd"},
{name:"Adriatic Mist",
hexvalue:"#d3ece4"},
{name:"Adriatic Sea",
hexvalue:"#016081"},
{name:"Adrift",
hexvalue:"#4b9099"},
{name:"Advantageous",
hexvalue:"#20726a"},
{name:"Adventure",
hexvalue:"#34788c"},
{name:"Adventure Island Pink",
hexvalue:"#f87858"},
{name:"Adventure Isle",
hexvalue:"#6f9fb9"},
{name:"Adventure Orange",
hexvalue:"#eda367"},
{name:"Adventurer",
hexvalue:"#72664f"},
{name:"Advertisement Green",
hexvalue:"#d8cb4b"},
{name:"Advertising Blue",
hexvalue:"#0081a8"},
{name:"Advertising Green",
hexvalue:"#53a079"},
{name:"Aebleskiver",
hexvalue:"#e6d3b6"},
{name:"Aegean Blue",
hexvalue:"#4e6e81"},
{name:"Aegean Green",
hexvalue:"#4c8c72"},
{name:"Aegean Mist",
hexvalue:"#9cbbe2"},
{name:"Aegean Sea",
hexvalue:"#508fa2"},
{name:"Aegean Sky",
hexvalue:"#e48b59"},
{name:"Aegean Splendor",
hexvalue:"#9ba0a4"},
{name:"Aerial View",
hexvalue:"#a0b2c8"},
{name:"Aero",
hexvalue:"#7cb9e8"},
{name:"Aero Blue",
hexvalue:"#c0e8d5"},
{name:"Aerobic Fix",
hexvalue:"#a2c348"},
{name:"Aeronautic",
hexvalue:"#2b3448"},
{name:"Aerospace Orange",
hexvalue:"#ff4f00"},
{name:"Aerostatics",
hexvalue:"#355376"},
{name:"Aesthetic White",
hexvalue:"#e3ddd3"},
{name:"Affair",
hexvalue:"#745085"},
{name:"Affen Turquoise",
hexvalue:"#aaffff"},
{name:"Affinity",
hexvalue:"#fed2a5"},
{name:"Afghan Carpet",
hexvalue:"#905e26"},
{name:"Afghan Hound",
hexvalue:"#e2d7b5"},
{name:"Afghan Sand",
hexvalue:"#d3a95c"},
{name:"Afloat",
hexvalue:"#78a3c2"},
{name:"African Ambush",
hexvalue:"#8e603c"},
{name:"African Bubinga",
hexvalue:"#c7927a"},
{name:"African Gray",
hexvalue:"#939899"},
{name:"African Mahogany",
hexvalue:"#cd4a4a"},
{name:"African Mud",
hexvalue:"#826c68"},
{name:"African Plain",
hexvalue:"#86714a"},
{name:"African Queen",
hexvalue:"#645e42"},
{name:"African Safari",
hexvalue:"#b16b40"},
{name:"African Sand",
hexvalue:"#ccaa88"},
{name:"African Violet",
hexvalue:"#b085b7"},
{name:"After Burn",
hexvalue:"#fd8b60"},
{name:"After Dark",
hexvalue:"#3c3535"},
{name:"After Dinner Mint",
hexvalue:"#e3f5e5"},
{name:"After Eight Filling",
hexvalue:"#d6eae8"},
{name:"After Midnight",
hexvalue:"#38393f"},
{name:"After Rain",
hexvalue:"#c1dbea"},
{name:"After Shock",
hexvalue:"#fec65f"},
{name:"After the Rain",
hexvalue:"#8bc4d1"},
{name:"After the Storm",
hexvalue:"#33616a"},
{name:"After Work Blue",
hexvalue:"#24246d"},
{name:"After-Party Pink",
hexvalue:"#c95efb"},
{name:"Aftercare",
hexvalue:"#85c0cd"},
{name:"Afterglow",
hexvalue:"#f3e6c9"},
{name:"Afterlife",
hexvalue:"#d91fff"},
{name:"Afternoon",
hexvalue:"#fbcb78"},
{name:"Afternoon Sky",
hexvalue:"#87ceeb"},
{name:"Afternoon Stroll",
hexvalue:"#d9c5a1"},
{name:"Afternoon Tea",
hexvalue:"#594e40"},
{name:"Agapanthus",
hexvalue:"#bbc5de"},
{name:"Agate Brown",
hexvalue:"#956a60"},
{name:"Agate Green",
hexvalue:"#599f99"},
{name:"Agate Grey",
hexvalue:"#b1b09f"},
{name:"Agate Violet",
hexvalue:"#5a5b74"},
{name:"Agave",
hexvalue:"#879d99"},
{name:"Agave Frond",
hexvalue:"#5a6e6a"},
{name:"Agave Green",
hexvalue:"#6b7169"},
{name:"Agave Plant",
hexvalue:"#879c67"},
{name:"Aged Beige",
hexvalue:"#d7cfc0"},
{name:"Aged Brandy",
hexvalue:"#87413f"},
{name:"Aged Chocolate",
hexvalue:"#5f4947"},
{name:"Aged Cotton",
hexvalue:"#e0dcda"},
{name:"Aged Eucalyptus",
hexvalue:"#898253"},
{name:"Aged Gouda",
hexvalue:"#dd9944"},
{name:"Aged Jade",
hexvalue:"#6c6956"},
{name:"Aged Merlot",
hexvalue:"#73343a"},
{name:"Aged Mustard Green",
hexvalue:"#6e6e30"},
{name:"Aged Olive",
hexvalue:"#7e7666"},
{name:"Aged Parchment",
hexvalue:"#e9ddca"},
{name:"Aged Pewter",
hexvalue:"#889999"},
{name:"Aged Pink",
hexvalue:"#c99f99"},
{name:"Aged Plastic Casing",
hexvalue:"#fffa86"},
{name:"Aged Purple",
hexvalue:"#a442a0"},
{name:"Aged Teak",
hexvalue:"#7a4134"},
{name:"Aged to Perfection",
hexvalue:"#a58ea9"},
{name:"Aged Whisky",
hexvalue:"#9d7147"},
{name:"Aged White",
hexvalue:"#e8decd"},
{name:"Aged Wine",
hexvalue:"#895460"},
{name:"Ageless",
hexvalue:"#ececdf"},
{name:"Ageless Beauty",
hexvalue:"#e7a995"},
{name:"Agent Orange",
hexvalue:"#ee6633"},
{name:"Aggressive Baby Blue",
hexvalue:"#6fffff"},
{name:"Aggressive Salmon",
hexvalue:"#ff7799"},
{name:"Aging Barrel",
hexvalue:"#6a5b4e"},
{name:"Agrax Earthshade",
hexvalue:"#393121"},
{name:"Agreeable Gray",
hexvalue:"#d1cbc1"},
{name:"Agrellan Badland",
hexvalue:"#ffb347"},
{name:"Agrellan Earth",
hexvalue:"#a17c59"},
{name:"Agressive Aqua",
hexvalue:"#00fbff"},
{name:"Agrodolce",
hexvalue:"#f0e2d3"},
{name:"Agua Fría",
hexvalue:"#9fc5cc"},
{name:"Ahaetulla Prasina",
hexvalue:"#00fa92"},
{name:"Ahmar Red",
hexvalue:"#c22147"},
{name:"Ahoy",
hexvalue:"#2a3149"},
{name:"Ahriman Blue",
hexvalue:"#199ebd"},
{name:"Ai Indigo",
hexvalue:"#274447"},
{name:"Aida",
hexvalue:"#b4c8b6"},
{name:"Aijiro White",
hexvalue:"#ecf7f7"},
{name:"Aimee",
hexvalue:"#eee5e1"},
{name:"Aimiru Brown",
hexvalue:"#2e372e"},
{name:"Air Blue",
hexvalue:"#77acc7"},
{name:"Air Castle",
hexvalue:"#d7d1e9"},
{name:"Air Force Blue",
hexvalue:"#5d8aa8"},
{name:"Air of Mint",
hexvalue:"#d8f2ee"},
{name:"Air Superiority Blue",
hexvalue:"#72a0c1"},
{name:"Airborne",
hexvalue:"#a2c2d0"},
{name:"Airbrushed Copper",
hexvalue:"#aa6c51"},
{name:"Aircraft Blue",
hexvalue:"#354f58"},
{name:"Aircraft Exterior Grey",
hexvalue:"#939498"},
{name:"Aircraft Green",
hexvalue:"#2a2c1f"},
{name:"Aircraft White",
hexvalue:"#edf2f8"},
{name:"Airflow",
hexvalue:"#d9e5e4"},
{name:"Airforce",
hexvalue:"#364d70"},
{name:"Airline Green",
hexvalue:"#8c9632"},
{name:"Airy",
hexvalue:"#dae6e9"},
{name:"Airy Blue",
hexvalue:"#88ccee"},
{name:"Airy Green",
hexvalue:"#dbe0c4"},
{name:"Ajo Lily",
hexvalue:"#faecd9"},
{name:"Ajwain Green",
hexvalue:"#d3de7b"},
{name:"Akabeni",
hexvalue:"#c3272b"},
{name:"Akai Red",
hexvalue:"#bc012e"},
{name:"Akakō Red",
hexvalue:"#f07f5e"},
{name:"Akaroa",
hexvalue:"#beb29a"},
{name:"Ake Blood",
hexvalue:"#cf3a24"},
{name:"Akebi Purple",
hexvalue:"#983fb2"},
{name:"Akebono Dawn",
hexvalue:"#fa7b62"},
{name:"Akhdhar Green",
hexvalue:"#b0e313"},
{name:"Akihabara Arcade",
hexvalue:"#601ef9"},
{name:"Akira Red",
hexvalue:"#e12120"},
{name:"Akuma's Fury",
hexvalue:"#871646"},
{name:"Alabama Crimson",
hexvalue:"#a32638"},
{name:"Alabaster",
hexvalue:"#f3e7db"},
{name:"Alabaster Beauty",
hexvalue:"#e9e3d2"},
{name:"Alabaster Gleam",
hexvalue:"#f0debd"},
{name:"Alabaster White",
hexvalue:"#dfd4bf"},
{name:"Aladdin's Feather",
hexvalue:"#5500ff"},
{name:"Alaea",
hexvalue:"#81585b"},
{name:"Alaitoc Blue",
hexvalue:"#8e8c97"},
{name:"Alajuela Toad",
hexvalue:"#ffae52"},
{name:"Alameda Ochre",
hexvalue:"#ca9234"},
{name:"Alamosa Green",
hexvalue:"#939b71"},
{name:"Alarm",
hexvalue:"#ec0003"},
{name:"Alarming Slime",
hexvalue:"#2ce335"},
{name:"Alaskan Blue",
hexvalue:"#6da9d2"},
{name:"Alaskan Cruise",
hexvalue:"#34466c"},
{name:"Alaskan Grey",
hexvalue:"#bcbebc"},
{name:"Alaskan Ice",
hexvalue:"#7e9ec2"},
{name:"Alaskan Mist",
hexvalue:"#ecf0e5"},
{name:"Alaskan Moss",
hexvalue:"#05472a"},
{name:"Alaskan Skies",
hexvalue:"#cddced"},
{name:"Alaskan Wind",
hexvalue:"#bae3eb"},
{name:"Albanian Red",
hexvalue:"#cc0001"},
{name:"Albeit",
hexvalue:"#38546e"},
{name:"Albert Green",
hexvalue:"#4f5845"},
{name:"Albescent White",
hexvalue:"#e1dacb"},
{name:"Albino",
hexvalue:"#fbeee5"},
{name:"Albuquerque",
hexvalue:"#cca47e"},
{name:"Alchemy",
hexvalue:"#e7cf8c"},
{name:"Aldabra",
hexvalue:"#aaa492"},
{name:"Alden Till",
hexvalue:"#7a4b49"},
{name:"Alert Tan",
hexvalue:"#954e2c"},
{name:"Alesan",
hexvalue:"#f1ceb3"},
{name:"Aleutian",
hexvalue:"#9a9eb3"},
{name:"Alexandra Peach",
hexvalue:"#db9785"},
{name:"Alexandria",
hexvalue:"#ff8f73"},
{name:"Alexandria's Lighthouse",
hexvalue:"#fcefc1"},
{name:"Alexandrian Sky",
hexvalue:"#bcd9dc"},
{name:"Alexandrite",
hexvalue:"#598c74"},
{name:"Alexandrite Green",
hexvalue:"#767853"},
{name:"Alexis Blue",
hexvalue:"#416082"},
{name:"Alfalfa",
hexvalue:"#b7b59f"},
{name:"Alfalfa Extract",
hexvalue:"#546940"},
{name:"Alga Moss",
hexvalue:"#8da98d"},
{name:"Algae",
hexvalue:"#54ac68"},
{name:"Algae Green",
hexvalue:"#93dfb8"},
{name:"Algae Red",
hexvalue:"#983d53"},
{name:"Algal Fuel",
hexvalue:"#21c36f"},
{name:"Algen Gerne",
hexvalue:"#479784"},
{name:"Algerian Coral",
hexvalue:"#fc5a50"},
{name:"Algiers Blue",
hexvalue:"#00859c"},
{name:"Algodon Azul",
hexvalue:"#c1dbec"},
{name:"Alhambra",
hexvalue:"#008778"},
{name:"Alhambra Cream",
hexvalue:"#f7f2e1"},
{name:"Alhambra Green",
hexvalue:"#00a465"},
{name:"Alibi",
hexvalue:"#d4cbc4"},
{name:"Alice Blue",
hexvalue:"#f0f8ff"},
{name:"Alice White",
hexvalue:"#c2ced2"},
{name:"Alien",
hexvalue:"#415764"},
{name:"Alien Abduction",
hexvalue:"#0cff0c"},
{name:"Alien Armpit",
hexvalue:"#84de02"},
{name:"Alien Breed",
hexvalue:"#b9cc81"},
{name:"Alien Parasite",
hexvalue:"#55ff33"},
{name:"Alien Purple",
hexvalue:"#490648"},
{name:"Alienator Grey",
hexvalue:"#9790a4"},
{name:"Align",
hexvalue:"#00728d"},
{name:"Alizarin",
hexvalue:"#e34636"},
{name:"Alizarin Crimson",
hexvalue:"#e32636"},
{name:"All About Olive",
hexvalue:"#676c58"},
{name:"All Dressed Up",
hexvalue:"#e6999d"},
{name:"All Made Up",
hexvalue:"#efd7e7"},
{name:"All Nighter",
hexvalue:"#455454"},
{name:"All's Ace",
hexvalue:"#c68886"},
{name:"Allegiance",
hexvalue:"#5a6a8c"},
{name:"Allegory",
hexvalue:"#b4b2a9"},
{name:"Allegro",
hexvalue:"#b28959"},
{name:"Alley",
hexvalue:"#b8c4d9"},
{name:"Alley Cat",
hexvalue:"#656874"},
{name:"Alliance",
hexvalue:"#2b655f"},
{name:"Alligator",
hexvalue:"#886600"},
{name:"Alligator Egg",
hexvalue:"#eaeed7"},
{name:"Alligator Gladiator",
hexvalue:"#444411"},
{name:"Alligator Skin",
hexvalue:"#646048"},
{name:"Allison Lace",
hexvalue:"#f1ead4"},
{name:"Allium",
hexvalue:"#9569a3"},
{name:"Alloy",
hexvalue:"#98979a"},
{name:"Alloy Orange",
hexvalue:"#c46210"},
{name:"Allports",
hexvalue:"#1f6a7d"},
{name:"Allspice",
hexvalue:"#f8cdaa"},
{name:"Allura Red",
hexvalue:"#ed2e38"},
{name:"Allure",
hexvalue:"#7291b4"},
{name:"Alluring Blue",
hexvalue:"#9ec4cd"},
{name:"Alluring Gesture",
hexvalue:"#f8dbc2"},
{name:"Alluring Light",
hexvalue:"#fff7d8"},
{name:"Alluring Umber",
hexvalue:"#977b4d"},
{name:"Alluring White",
hexvalue:"#efe1d2"},
{name:"Alluvial Inca",
hexvalue:"#bb934b"},
{name:"Allyson",
hexvalue:"#cb738b"},
{name:"Almeja",
hexvalue:"#f5e0c9"},
{name:"Almendra Tostada",
hexvalue:"#e8d6bd"},
{name:"Almond",
hexvalue:"#eddcc8"},
{name:"Almond Beige",
hexvalue:"#dfd5ca"},
{name:"Almond Biscuit",
hexvalue:"#e9c9a9"},
{name:"Almond Blossom",
hexvalue:"#f5bec7"},
{name:"Almond Blossom Pink",
hexvalue:"#e0d2d1"},
{name:"Almond Brittle",
hexvalue:"#e5d3b9"},
{name:"Almond Buff",
hexvalue:"#ccb390"},
{name:"Almond Butter",
hexvalue:"#d8c6a8"},
{name:"Almond Cookie",
hexvalue:"#eec87c"},
{name:"Almond Cream",
hexvalue:"#f4c29f"},
{name:"Almond Frost",
hexvalue:"#9a8678"},
{name:"Almond Green",
hexvalue:"#595e4c"},
{name:"Almond Icing",
hexvalue:"#efe3d9"},
{name:"Almond Kiss",
hexvalue:"#f6e3d4"},
{name:"Almond Latte",
hexvalue:"#d6c0a4"},
{name:"Almond Milk",
hexvalue:"#d6cebe"},
{name:"Almond Oil",
hexvalue:"#f4efc1"},
{name:"Almond Paste",
hexvalue:"#e5dbc5"},
{name:"Almond Roca",
hexvalue:"#f0e8e0"},
{name:"Almond Rose",
hexvalue:"#cc8888"},
{name:"Almond Silk",
hexvalue:"#e1cfb2"},
{name:"Almond Toast",
hexvalue:"#bf9e77"},
{name:"Almond Truffle",
hexvalue:"#7d665b"},
{name:"Almond Willow",
hexvalue:"#e6c9bc"},
{name:"Almond Wisp",
hexvalue:"#d6cab9"},
{name:"Almondine",
hexvalue:"#fedebc"},
{name:"Almost Aloe",
hexvalue:"#bfe5b1"},
{name:"Almost Apricot",
hexvalue:"#e5b39b"},
{name:"Almost Aqua",
hexvalue:"#98ddc5"},
{name:"Almost Famous",
hexvalue:"#3a5457"},
{name:"Almost Mauve",
hexvalue:"#e7dcd9"},
{name:"Almost Pink",
hexvalue:"#f0e3da"},
{name:"Aloe",
hexvalue:"#817a60"},
{name:"Aloe Blossom",
hexvalue:"#c97863"},
{name:"Aloe Cream",
hexvalue:"#dbe5b9"},
{name:"Aloe Essence",
hexvalue:"#ecf1e2"},
{name:"Aloe Leaf",
hexvalue:"#61643f"},
{name:"Aloe Mist",
hexvalue:"#dcf2e3"},
{name:"Aloe Nectar",
hexvalue:"#dfe2c9"},
{name:"Aloe Plant",
hexvalue:"#b8ba87"},
{name:"Aloe Thorn",
hexvalue:"#888b73"},
{name:"Aloe Vera",
hexvalue:"#678779"},
{name:"Aloe Vera Green",
hexvalue:"#7e9b39"},
{name:"Aloe Vera Tea",
hexvalue:"#848b71"},
{name:"Aloe Wash",
hexvalue:"#d0d3b7"},
{name:"Aloeswood",
hexvalue:"#6a432d"},
{name:"Aloha",
hexvalue:"#1db394"},
{name:"Aloha Sunset",
hexvalue:"#e9aa91"},
{name:"Alone in the Dark",
hexvalue:"#000066"},
{name:"Aloof",
hexvalue:"#d4e2e6"},
{name:"Aloof Gray",
hexvalue:"#c9c9c0"},
{name:"Aloof Lama",
hexvalue:"#d6c5a0"},
{name:"Alpaca",
hexvalue:"#f7e5da"},
{name:"Alpaca Blanket",
hexvalue:"#ded7c5"},
{name:"Alpaca Wool",
hexvalue:"#f9ede2"},
{name:"Alpenglow",
hexvalue:"#f0beb8"},
{name:"Alpha Blue",
hexvalue:"#588bb4"},
{name:"Alpha Centauri",
hexvalue:"#4d5778"},
{name:"Alpha Gold",
hexvalue:"#ae8e5f"},
{name:"Alpha Male",
hexvalue:"#715a45"},
{name:"Alpha Tango",
hexvalue:"#628fb0"},
{name:"Alphabet Blue",
hexvalue:"#abcdef"},
{name:"Alpine",
hexvalue:"#ad8a3b"},
{name:"Alpine Air",
hexvalue:"#a9b4a9"},
{name:"Alpine Alabaster",
hexvalue:"#badbe6"},
{name:"Alpine Berry Yellow",
hexvalue:"#f7e0ba"},
{name:"Alpine Blue",
hexvalue:"#dbe4e5"},
{name:"Alpine Duck Grey",
hexvalue:"#40464d"},
{name:"Alpine Expedition",
hexvalue:"#99eeff"},
{name:"Alpine Frost",
hexvalue:"#e0ded2"},
{name:"Alpine Goat",
hexvalue:"#f1f2f8"},
{name:"Alpine Green",
hexvalue:"#005f56"},
{name:"Alpine Haze",
hexvalue:"#abbec0"},
{name:"Alpine Herbs",
hexvalue:"#449955"},
{name:"Alpine Lake Green",
hexvalue:"#4f603e"},
{name:"Alpine Landing",
hexvalue:"#117b87"},
{name:"Alpine Moon",
hexvalue:"#ded3e6"},
{name:"Alpine Morning Blue",
hexvalue:"#a6ccd8"},
{name:"Alpine Race",
hexvalue:"#234162"},
{name:"Alpine Salamander",
hexvalue:"#051009"},
{name:"Alpine Summer",
hexvalue:"#a5a99a"},
{name:"Alpine Trail",
hexvalue:"#515a52"},
{name:"Alsike Clover Red",
hexvalue:"#b1575f"},
{name:"Alsot Olive",
hexvalue:"#dfd5b1"},
{name:"Altar of Heaven",
hexvalue:"#4d4c80"},
{name:"Altdorf Guard Blue",
hexvalue:"#1f56a7"},
{name:"Altdorf Sky Blue",
hexvalue:"#00a1ac"},
{name:"Alter Ego",
hexvalue:"#69656d"},
{name:"Altered Pink",
hexvalue:"#efc7be"},
{name:"Alto",
hexvalue:"#cdc6c5"},
{name:"Alu Gobi",
hexvalue:"#ddbb00"},
{name:"Alucard's Night",
hexvalue:"#000055"},
{name:"Aluminium",
hexvalue:"#848789"},
{name:"Aluminium Powder",
hexvalue:"#a9a0a9"},
{name:"Aluminium Snow",
hexvalue:"#aeafb4"},
{name:"Aluminum",
hexvalue:"#9f9586"},
{name:"Aluminum Foil",
hexvalue:"#d2d9db"},
{name:"Aluminum Silver",
hexvalue:"#8c8d91"},
{name:"Aluminum Sky",
hexvalue:"#adafaf"},
{name:"Alverda",
hexvalue:"#a5c970"},
{name:"Always Almond",
hexvalue:"#ebe5d2"},
{name:"Always Apple",
hexvalue:"#a0a667"},
{name:"Always Blue",
hexvalue:"#a2bacb"},
{name:"Always Green Grass",
hexvalue:"#11aa00"},
{name:"Always Indigo",
hexvalue:"#66778c"},
{name:"Always Neutral",
hexvalue:"#dfd7cb"},
{name:"Always Rosey",
hexvalue:"#e79db3"},
{name:"Alyssa",
hexvalue:"#f4e2d6"},
{name:"Alyssum",
hexvalue:"#f2d5d7"},
{name:"Amalfi",
hexvalue:"#016e85"},
{name:"Amalfi Coast",
hexvalue:"#297cbf"},
{name:"Amalfitan Azure",
hexvalue:"#033b9a"},
{name:"Amaranth",
hexvalue:"#e86ead"},
{name:"Amaranth Blossom",
hexvalue:"#7b2331"},
{name:"Amaranth Deep Purple",
hexvalue:"#9f2b68"},
{name:"Amaranth Pink",
hexvalue:"#f19cbb"},
{name:"Amaranth Purple",
hexvalue:"#6a397b"},
{name:"Amaranth Red",
hexvalue:"#d3212d"},
{name:"Amarantha Red",
hexvalue:"#cc3311"},
{name:"Amaranthine",
hexvalue:"#5f4053"},
{name:"Amaretto",
hexvalue:"#ab6f60"},
{name:"Amaretto Sour",
hexvalue:"#c09856"},
{name:"Amarillo Bebito",
hexvalue:"#fff1d4"},
{name:"Amarillo Yellow",
hexvalue:"#fbf1c3"},
{name:"Amarklor Violet",
hexvalue:"#551199"},
{name:"Amaryllis",
hexvalue:"#b85045"},
{name:"Amaya",
hexvalue:"#f2c1cb"},
{name:"Amazing Amethyst",
hexvalue:"#806568"},
{name:"Amazing Boulder",
hexvalue:"#a9a797"},
{name:"Amazing Gray",
hexvalue:"#beb5a9"},
{name:"Amazing Smoke",
hexvalue:"#6680bb"},
{name:"Amazon",
hexvalue:"#387b54"},
{name:"Amazon Breeze",
hexvalue:"#ebebd6"},
{name:"Amazon Depths",
hexvalue:"#505338"},
{name:"Amazon Foliage",
hexvalue:"#606553"},
{name:"Amazon Green",
hexvalue:"#786a4a"},
{name:"Amazon Jungle",
hexvalue:"#686747"},
{name:"Amazon Mist",
hexvalue:"#ececdc"},
{name:"Amazon Moss",
hexvalue:"#7e8c7a"},
{name:"Amazon Queen",
hexvalue:"#948f54"},
{name:"Amazon River",
hexvalue:"#777462"},
{name:"Amazon River Dolphin",
hexvalue:"#e6b2b8"},
{name:"Amazon Stone",
hexvalue:"#7e7873"},
{name:"Amazon Vine",
hexvalue:"#abaa97"},
{name:"Amazonian",
hexvalue:"#aa6644"},
{name:"Amazonian Orchid",
hexvalue:"#a7819d"},
{name:"Amazonite",
hexvalue:"#00c4b0"},
{name:"Ambassador Blue",
hexvalue:"#0d2f5a"},
{name:"Amber",
hexvalue:"#ffbf00"},
{name:"Amber Autumn",
hexvalue:"#c69c6a"},
{name:"Amber Brew",
hexvalue:"#d7a361"},
{name:"Amber Brown",
hexvalue:"#a66646"},
{name:"Amber Dawn",
hexvalue:"#f6bc77"},
{name:"Amber Glass",
hexvalue:"#c79958"},
{name:"Amber Glow",
hexvalue:"#f29a39"},
{name:"Amber Gold",
hexvalue:"#c19552"},
{name:"Amber Green",
hexvalue:"#9a803a"},
{name:"Amber Grey",
hexvalue:"#d0a592"},
{name:"Amber Leaf",
hexvalue:"#ba9971"},
{name:"Amber Moon",
hexvalue:"#eed1a5"},
{name:"Amber Romance",
hexvalue:"#b18140"},
{name:"Amber Sun",
hexvalue:"#ff9988"},
{name:"Amber Tide",
hexvalue:"#ffafa3"},
{name:"Amber Wave",
hexvalue:"#d78b55"},
{name:"Amber Yellow",
hexvalue:"#fab75a"},
{name:"Amberglow",
hexvalue:"#dc793e"},
{name:"Amberlight",
hexvalue:"#e2bea2"},
{name:"Ambience White",
hexvalue:"#e7e7e6"},
{name:"Ambient Glow",
hexvalue:"#f8ede0"},
{name:"Ambit",
hexvalue:"#97653f"},
{name:"Ambitious Amber",
hexvalue:"#f0cb97"},
{name:"Ambitious Rose",
hexvalue:"#e9687e"},
{name:"Ambrosia",
hexvalue:"#d2e7ca"},
{name:"Ambrosia Coffee Cake",
hexvalue:"#eee9d3"},
{name:"Ambrosia Ivory",
hexvalue:"#fff4eb"},
{name:"Ambrosia Salad",
hexvalue:"#f4ded3"},
{name:"Ameixa",
hexvalue:"#6a5acd"},
{name:"Amelia",
hexvalue:"#beccc2"},
{name:"Amélie's Tutu",
hexvalue:"#fea7bd"},
{name:"America's Cup",
hexvalue:"#34546d"},
{name:"American Anthem",
hexvalue:"#7595ab"},
{name:"American Beauty",
hexvalue:"#a73340"},
{name:"American Blue",
hexvalue:"#3b3b6d"},
{name:"American Bronze",
hexvalue:"#391802"},
{name:"American Brown",
hexvalue:"#804040"},
{name:"American Gold",
hexvalue:"#d3af37"},
{name:"American Green",
hexvalue:"#34b334"},
{name:"American Mahogany",
hexvalue:"#52352f"},
{name:"American Milking Devon",
hexvalue:"#63403a"},
{name:"American Orange",
hexvalue:"#ff8b00"},
{name:"American Pink",
hexvalue:"#ff9899"},
{name:"American Purple",
hexvalue:"#431c53"},
{name:"American Red",
hexvalue:"#b32134"},
{name:"American River",
hexvalue:"#626e71"},
{name:"American Roast",
hexvalue:"#995544"},
{name:"American Rose",
hexvalue:"#ff033e"},
{name:"American Silver",
hexvalue:"#cfcfcf"},
{name:"American Violet",
hexvalue:"#551b8c"},
{name:"American Yellow",
hexvalue:"#f2b400"},
{name:"American Yorkshire",
hexvalue:"#efdcd4"},
{name:"Americana",
hexvalue:"#0477b4"},
{name:"Americano",
hexvalue:"#463732"},
{name:"Amethyst",
hexvalue:"#9966cc"},
{name:"Amethyst Cream",
hexvalue:"#eceaec"},
{name:"Amethyst Dark Violet",
hexvalue:"#4f3c52"},
{name:"Amethyst Ganzstar",
hexvalue:"#8f00ff"},
{name:"Amethyst Gem",
hexvalue:"#776985"},
{name:"Amethyst Grey",
hexvalue:"#9085c4"},
{name:"Amethyst Grey Violet",
hexvalue:"#9c89a1"},
{name:"Amethyst Haze",
hexvalue:"#a0a0aa"},
{name:"Amethyst Ice",
hexvalue:"#d0c9c6"},
{name:"Amethyst Light Violet",
hexvalue:"#cfc2d1"},
{name:"Amethyst Orchid",
hexvalue:"#926aa6"},
{name:"Amethyst Paint",
hexvalue:"#9c8aa4"},
{name:"Amethyst Phlox",
hexvalue:"#9b91a1"},
{name:"Amethyst Purple",
hexvalue:"#562f7e"},
{name:"Amethyst Show",
hexvalue:"#bd97cf"},
{name:"Amethyst Smoke",
hexvalue:"#95879c"},
{name:"Ametrine Quartz",
hexvalue:"#ded1e0"},
{name:"Amiable Orange",
hexvalue:"#df965b"},
{name:"Amish Bread",
hexvalue:"#e6ddbe"},
{name:"Amish Green",
hexvalue:"#3a5f4e"},
{name:"Amnesia Blue",
hexvalue:"#1560bd"},
{name:"Amok",
hexvalue:"#ddcc22"},
{name:"Amor",
hexvalue:"#ee3377"},
{name:"Amora Purple",
hexvalue:"#bb22aa"},
{name:"Amore",
hexvalue:"#ae2f48"},
{name:"Amorphous Rose",
hexvalue:"#b1a7b7"},
{name:"Amour",
hexvalue:"#ee5851"},
{name:"Amour Frais",
hexvalue:"#f5e6ea"},
{name:"Amourette",
hexvalue:"#c8c5d7"},
{name:"Amourette Eternelle",
hexvalue:"#e0dfe8"},
{name:"Amparo Blue",
hexvalue:"#4960a8"},
{name:"Amphibian",
hexvalue:"#264c47"},
{name:"Amphitrite",
hexvalue:"#384e47"},
{name:"Amphora",
hexvalue:"#9f8672"},
{name:"Amphystine",
hexvalue:"#3f425a"},
{name:"Amulet",
hexvalue:"#7d9d72"},
{name:"Amulet Gem",
hexvalue:"#01748e"},
{name:"Amygdala Purple",
hexvalue:"#69045f"},
{name:"Àn Zǐ Purple",
hexvalue:"#94568c"},
{name:"Anaheim Pepper",
hexvalue:"#00bb44"},
{name:"Anakiwa",
hexvalue:"#8cceea"},
{name:"Analytical Gray",
hexvalue:"#bfb6a7"},
{name:"Anarchist",
hexvalue:"#db304a"},
{name:"Anarchy",
hexvalue:"#de0300"},
{name:"Ancestral",
hexvalue:"#d0c1c3"},
{name:"Ancestral Gold",
hexvalue:"#ddcda6"},
{name:"Ancestral Water",
hexvalue:"#d0d0d0"},
{name:"Ancestry Violet",
hexvalue:"#9e90a7"},
{name:"Ancho Pepper",
hexvalue:"#7a5145"},
{name:"Anchor Grey",
hexvalue:"#596062"},
{name:"Anchor Point",
hexvalue:"#435d8b"},
{name:"Anchorman",
hexvalue:"#2c3641"},
{name:"Anchors Away",
hexvalue:"#9ebbcd"},
{name:"Anchors Aweigh",
hexvalue:"#2b3441"},
{name:"Anchovy",
hexvalue:"#756f6b"},
{name:"Ancient Bamboo",
hexvalue:"#da6304"},
{name:"Ancient Brandy",
hexvalue:"#aa6611"},
{name:"Ancient Bronze",
hexvalue:"#9c5221"},
{name:"Ancient Chest",
hexvalue:"#99522b"},
{name:"Ancient Copper",
hexvalue:"#9f543e"},
{name:"Ancient Doeskin",
hexvalue:"#dcc9a8"},
{name:"Ancient Earth",
hexvalue:"#746550"},
{name:"Ancient Ice",
hexvalue:"#73fdff"},
{name:"Ancient Ivory",
hexvalue:"#f1e6d1"},
{name:"Ancient Kingdom",
hexvalue:"#d6d8cd"},
{name:"Ancient Lavastone",
hexvalue:"#483c32"},
{name:"Ancient Magenta",
hexvalue:"#953d55"},
{name:"Ancient Marble",
hexvalue:"#d1ccb9"},
{name:"Ancient Maze",
hexvalue:"#959651"},
{name:"Ancient Murasaki Purple",
hexvalue:"#895b8a"},
{name:"Ancient Olive",
hexvalue:"#6a5536"},
{name:"Ancient Pages",
hexvalue:"#ddd4ce"},
{name:"Ancient Pewter",
hexvalue:"#898d91"},
{name:"Ancient Planks",
hexvalue:"#774411"},
{name:"Ancient Pottery",
hexvalue:"#a37d5e"},
{name:"Ancient Prunus",
hexvalue:"#5a3d3f"},
{name:"Ancient Red",
hexvalue:"#922a31"},
{name:"Ancient Root",
hexvalue:"#70553d"},
{name:"Ancient Royal Banner",
hexvalue:"#843f5b"},
{name:"Ancient Ruins",
hexvalue:"#e0cac0"},
{name:"Ancient Scroll",
hexvalue:"#f5e6de"},
{name:"Ancient Shelter",
hexvalue:"#83696e"},
{name:"Ancient Stone",
hexvalue:"#ded8d4"},
{name:"Ancient Yellow",
hexvalue:"#eecd00"},
{name:"Andean Opal Green",
hexvalue:"#afcdc7"},
{name:"Andean Slate",
hexvalue:"#90b19d"},
{name:"Andes Ash",
hexvalue:"#c1a097"},
{name:"Andes Sky",
hexvalue:"#78d8d9"},
{name:"Andiron",
hexvalue:"#424036"},
{name:"Andorra",
hexvalue:"#603535"},
{name:"Andouille",
hexvalue:"#b58338"},
{name:"Andover Cream",
hexvalue:"#faf0d3"},
{name:"Andrea Blue",
hexvalue:"#4477dd"},
{name:"Android Green",
hexvalue:"#a4c639"},
{name:"Andromeda Blue",
hexvalue:"#abcdee"},
{name:"Anemone",
hexvalue:"#842c48"},
{name:"Anemone White",
hexvalue:"#f9efe4"},
{name:"Anew Gray",
hexvalue:"#beb6ab"},
{name:"Angel Aura",
hexvalue:"#afa8ae"},
{name:"Angel Blue",
hexvalue:"#83c5cd"},
{name:"Angel Blush",
hexvalue:"#f7e3da"},
{name:"Angel Breath",
hexvalue:"#dcaf9f"},
{name:"Angel Face Rose",
hexvalue:"#fe83cc"},
{name:"Angel Falls",
hexvalue:"#a3bdd3"},
{name:"Angel Feather",
hexvalue:"#f4efee"},
{name:"Angel Finger",
hexvalue:"#b8acb4"},
{name:"Angel Food",
hexvalue:"#f0e8d9"},
{name:"Angel Food Cake",
hexvalue:"#d7a14f"},
{name:"Angel Green",
hexvalue:"#004225"},
{name:"Angel Hair Silver",
hexvalue:"#d2d6db"},
{name:"Angel Heart",
hexvalue:"#a17791"},
{name:"Angel in Blue Jeans",
hexvalue:"#bbc6d9"},
{name:"Angel Kiss",
hexvalue:"#cec7dc"},
{name:"Angel of Death Victorious",
hexvalue:"#c6f0e7"},
{name:"Angel Shark",
hexvalue:"#e19640"},
{name:"Angel Wing",
hexvalue:"#f3dfd7"},
{name:"Angel's Face",
hexvalue:"#eed4c8"},
{name:"Angel's Feather",
hexvalue:"#f3f1e6"},
{name:"Angel's Whisper",
hexvalue:"#dbdfd4"},
{name:"Angela Bay",
hexvalue:"#a9c1e5"},
{name:"Angela Canyon",
hexvalue:"#c99997"},
{name:"Angelic",
hexvalue:"#f2dcd7"},
{name:"Angelic Blue",
hexvalue:"#bbc6d6"},
{name:"Angelic Choir",
hexvalue:"#e9d9dc"},
{name:"Angelic Descent",
hexvalue:"#eecc33"},
{name:"Angelic Eyes",
hexvalue:"#bbd1e8"},
{name:"Angelic Sent",
hexvalue:"#e3dfea"},
{name:"Angelic Starlet",
hexvalue:"#ebe9d8"},
{name:"Angelic White",
hexvalue:"#f4ede4"},
{name:"Angelico",
hexvalue:"#eacfc2"},
{name:"Angélique Grey",
hexvalue:"#d8dee7"},
{name:"Anger",
hexvalue:"#dd0055"},
{name:"Angora",
hexvalue:"#dfd1bb"},
{name:"Angora Blue",
hexvalue:"#b9c6d8"},
{name:"Angora Goat",
hexvalue:"#ede7de"},
{name:"Angora Pink",
hexvalue:"#ebdfea"},
{name:"Angraecum Orchid",
hexvalue:"#f4f6ec"},
{name:"Angry Flamingo",
hexvalue:"#f04e45"},
{name:"Angry Gargoyle",
hexvalue:"#9799a6"},
{name:"Angry Ghost",
hexvalue:"#eebbbb"},
{name:"Angry Gremlin",
hexvalue:"#37503d"},
{name:"Angry Hornet",
hexvalue:"#ee9911"},
{name:"Angry Ocean",
hexvalue:"#4e6665"},
{name:"Angry Pasta",
hexvalue:"#ffcc55"},
{name:"Aniline Mauve",
hexvalue:"#b9abad"},
{name:"Animal Blood",
hexvalue:"#a41313"},
{name:"Animal Cracker",
hexvalue:"#f4e6ce"},
{name:"Animal Kingdom",
hexvalue:"#bcc09e"},
{name:"Animated Coral",
hexvalue:"#ed9080"},
{name:"Animation",
hexvalue:"#1d5c83"},
{name:"Anime",
hexvalue:"#ccc14d"},
{name:"Anise Biscotti",
hexvalue:"#c0baaf"},
{name:"Anise Flower",
hexvalue:"#f4e3b5"},
{name:"Anise Grey Yellow",
hexvalue:"#b0ac98"},
{name:"Aniseed Leaf Green",
hexvalue:"#8cb684"},
{name:"Anita",
hexvalue:"#91a0b7"},
{name:"Anjou Pear",
hexvalue:"#cdca9f"},
{name:"Annabel",
hexvalue:"#f7efcf"},
{name:"Annapolis Blue",
hexvalue:"#384a66"},
{name:"Annis",
hexvalue:"#6b475d"},
{name:"Annular",
hexvalue:"#e17861"},
{name:"Anode",
hexvalue:"#89a4cd"},
{name:"Anon",
hexvalue:"#bdbfc8"},
{name:"Anonymous",
hexvalue:"#dadcd3"},
{name:"Another One Bites the Dust",
hexvalue:"#c7bba4"},
{name:"Ant Red",
hexvalue:"#b05d4a"},
{name:"Antarctic Blue",
hexvalue:"#2b3f5c"},
{name:"Antarctic Circle",
hexvalue:"#0000bb"},
{name:"Antarctic Deep",
hexvalue:"#35383f"},
{name:"Antarctica",
hexvalue:"#c6c5c6"},
{name:"Antarctica Lake",
hexvalue:"#bfd2d0"},
{name:"Antelope",
hexvalue:"#b19664"},
{name:"Anthill",
hexvalue:"#7f684e"},
{name:"Anthracite",
hexvalue:"#28282d"},
{name:"Anthracite Blue",
hexvalue:"#3d475e"},
{name:"Anthracite Grey",
hexvalue:"#373f42"},
{name:"Anthracite Red",
hexvalue:"#73293b"},
{name:"Anti Rainbow Grey",
hexvalue:"#bebdbc"},
{name:"Anti-Flash White",
hexvalue:"#f2f3f4"},
{name:"Antigua",
hexvalue:"#256d73"},
{name:"Antigua Blue",
hexvalue:"#06b1c4"},
{name:"Antigua Sand",
hexvalue:"#83c2cd"},
{name:"Antigua Sunrise",
hexvalue:"#ffe7c8"},
{name:"Antilles Blue",
hexvalue:"#3b5e8d"},
{name:"Antilles Garden",
hexvalue:"#8aa277"},
{name:"Antimony",
hexvalue:"#c7c8c1"},
{name:"Antiquarian Brown",
hexvalue:"#946644"},
{name:"Antiquarian Gold",
hexvalue:"#ba8a45"},
{name:"Antiquate",
hexvalue:"#8d8aa0"},
{name:"Antique",
hexvalue:"#8b846d"},
{name:"Antique Bear",
hexvalue:"#9c867b"},
{name:"Antique Bourbon",
hexvalue:"#926b43"},
{name:"Antique Brass",
hexvalue:"#6c461f"},
{name:"Antique Bronze",
hexvalue:"#704a07"},
{name:"Antique Brown",
hexvalue:"#553f2d"},
{name:"Antique Cameo",
hexvalue:"#f0baa4"},
{name:"Antique Candle Light",
hexvalue:"#f4e1d6"},
{name:"Antique Chest",
hexvalue:"#a7856d"},
{name:"Antique China",
hexvalue:"#fdf6e7"},
{name:"Antique Coin",
hexvalue:"#b5b8a8"},
{name:"Antique Copper",
hexvalue:"#9e6649"},
{name:"Antique Coral",
hexvalue:"#ffc7b0"},
{name:"Antique Earth",
hexvalue:"#7e6c5f"},
{name:"Antique Fuchsia",
hexvalue:"#915c83"},
{name:"Antique Garnet",
hexvalue:"#8e5e5e"},
{name:"Antique Gold",
hexvalue:"#b59e5f"},
{name:"Antique Green",
hexvalue:"#29675c"},
{name:"Antique Grey",
hexvalue:"#69576d"},
{name:"Antique Heather",
hexvalue:"#cdbacb"},
{name:"Antique Honey",
hexvalue:"#b39355"},
{name:"Antique Hot Pink",
hexvalue:"#b07f9e"},
{name:"Antique Ivory",
hexvalue:"#f9ecd3"},
{name:"Antique Lace",
hexvalue:"#fdf2db"},
{name:"Antique Leather",
hexvalue:"#9e8e7e"},
{name:"Antique Linen",
hexvalue:"#faeedb"},
{name:"Antique Marble",
hexvalue:"#f1e9d7"},
{name:"Antique Mauve",
hexvalue:"#bbb0b1"},
{name:"Antique Moss",
hexvalue:"#7a973b"},
{name:"Antique Paper",
hexvalue:"#f4f0e8"},
{name:"Antique Parchment",
hexvalue:"#ead8c1"},
{name:"Antique Pearl",
hexvalue:"#ebd7cb"},
{name:"Antique Penny",
hexvalue:"#957747"},
{name:"Antique Petal",
hexvalue:"#e8e3e3"},
{name:"Antique Pink",
hexvalue:"#c27a74"},
{name:"Antique Red",
hexvalue:"#7d4f51"},
{name:"Antique Rose",
hexvalue:"#997165"},
{name:"Antique Rosewood",
hexvalue:"#72393f"},
{name:"Antique Ruby",
hexvalue:"#841b2d"},
{name:"Antique Silver",
hexvalue:"#918e8c"},
{name:"Antique Tin",
hexvalue:"#6e7173"},
{name:"Antique Treasure",
hexvalue:"#bb9973"},
{name:"Antique Turquoise",
hexvalue:"#004e4e"},
{name:"Antique Viola",
hexvalue:"#928ba6"},
{name:"Antique White",
hexvalue:"#ece6d5"},
{name:"Antique Wicker Basket",
hexvalue:"#f3d3a1"},
{name:"Antique Windmill",
hexvalue:"#b6a38d"},
{name:"Antiqued Aqua",
hexvalue:"#bdccc1"},
{name:"Antiquities",
hexvalue:"#8a6c57"},
{name:"Antiquity",
hexvalue:"#c1a87c"},
{name:"Antler",
hexvalue:"#957a76"},
{name:"Antler Moth",
hexvalue:"#864f3e"},
{name:"Antler Velvet",
hexvalue:"#c0ad96"},
{name:"Antoinette",
hexvalue:"#b09391"},
{name:"Antoinette Pink",
hexvalue:"#e7c2b4"},
{name:"Anubis Black",
hexvalue:"#312231"},
{name:"Anzac",
hexvalue:"#c68e3f"},
{name:"Ao",
hexvalue:"#00800c"},
{name:"Aoife's Green",
hexvalue:"#27b692"},
{name:"Aotake Bamboo",
hexvalue:"#006442"},
{name:"Apatite Blue",
hexvalue:"#31827b"},
{name:"Apatite Crystal Green",
hexvalue:"#bbff99"},
{name:"Apeland",
hexvalue:"#8a843b"},
{name:"Aphrodite's Pearls",
hexvalue:"#eeffff"},
{name:"Aphroditean Fuschia",
hexvalue:"#dd14ab"},
{name:"Apium",
hexvalue:"#b5d0a2"},
{name:"Apnea Dive",
hexvalue:"#284fbd"},
{name:"Apocalyptic Orange",
hexvalue:"#f4711e"},
{name:"Apocyan",
hexvalue:"#99ccff"},
{name:"Apollo Bay",
hexvalue:"#748697"},
{name:"Apollo Landing",
hexvalue:"#e5e5e1"},
{name:"Apollo's White",
hexvalue:"#ddffff"},
{name:"Appalachian Forest",
hexvalue:"#848b80"},
{name:"Appalachian Trail",
hexvalue:"#cfb989"},
{name:"Appaloosa Spots",
hexvalue:"#876e52"},
{name:"Apparition",
hexvalue:"#c2bca9"},
{name:"Appetite",
hexvalue:"#b1e5aa"},
{name:"Appetizing Asparagus",
hexvalue:"#66aa00"},
{name:"Applause Please",
hexvalue:"#858c9b"},
{name:"Apple Blossom",
hexvalue:"#ddbca0"},
{name:"Apple Bob",
hexvalue:"#d5e69d"},
{name:"Apple Brown Betty",
hexvalue:"#9c6757"},
{name:"Apple Butter",
hexvalue:"#844b4d"},
{name:"Apple Cherry",
hexvalue:"#f81404"},
{name:"Apple Cider",
hexvalue:"#da995f"},
{name:"Apple Cinnamon",
hexvalue:"#b0885a"},
{name:"Apple Core",
hexvalue:"#f4eed8"},
{name:"Apple Cream",
hexvalue:"#b8d7a6"},
{name:"Apple Crisp",
hexvalue:"#e19c55"},
{name:"Apple Crunch",
hexvalue:"#fee5c9"},
{name:"Apple Cucumber",
hexvalue:"#dbdbbc"},
{name:"Apple Custard",
hexvalue:"#fddfae"},
{name:"Apple Day",
hexvalue:"#7e976d"},
{name:"Apple Flower",
hexvalue:"#edf4eb"},
{name:"Apple Green",
hexvalue:"#76cd26"},
{name:"Apple Herb Black",
hexvalue:"#4b4247"},
{name:"Apple Hill",
hexvalue:"#a69f8d"},
{name:"Apple Ice",
hexvalue:"#bdd0b1"},
{name:"Apple II Beige",
hexvalue:"#bfca87"},
{name:"Apple II Blue",
hexvalue:"#93d6bf"},
{name:"Apple II Chocolate",
hexvalue:"#da680e"},
{name:"Apple II Green",
hexvalue:"#04650d"},
{name:"Apple II Lime",
hexvalue:"#25c40d"},
{name:"Apple II Magenta",
hexvalue:"#dc41f1"},
{name:"Apple II Rose",
hexvalue:"#ac667b"},
{name:"Apple Infusion",
hexvalue:"#ddaabb"},
{name:"Apple Jack",
hexvalue:"#8b974e"},
{name:"Apple Martini",
hexvalue:"#f9fdd9"},
{name:"Apple Orchard",
hexvalue:"#93c96a"},
{name:"Apple Pie",
hexvalue:"#caab94"},
{name:"Apple Polish",
hexvalue:"#883e3f"},
{name:"Apple Sauce",
hexvalue:"#f4ebd2"},
{name:"Apple Seed",
hexvalue:"#a77c53"},
{name:"Apple Slice",
hexvalue:"#f1f0bf"},
{name:"Apple Turnover",
hexvalue:"#e8c194"},
{name:"Apple Valley",
hexvalue:"#ea8386"},
{name:"Apple Wine",
hexvalue:"#b59f62"},
{name:"Apple-A-Day",
hexvalue:"#903f45"},
{name:"Appleblossom",
hexvalue:"#dab5b4"},
{name:"Applegate",
hexvalue:"#8ac479"},
{name:"Applegate Park",
hexvalue:"#aead93"},
{name:"Applemint",
hexvalue:"#cdeacd"},
{name:"Applemint Soda",
hexvalue:"#f3f5e9"},
{name:"Applesauce",
hexvalue:"#f6d699"},
{name:"Applesauce Cake",
hexvalue:"#c2a377"},
{name:"Appletini",
hexvalue:"#929637"},
{name:"Appleton",
hexvalue:"#6eb478"},
{name:"Approaching Dusk",
hexvalue:"#8b97a5"},
{name:"Approval Green",
hexvalue:"#039487"},
{name:"Apricot",
hexvalue:"#ffb16d"},
{name:"Apricot Appeal",
hexvalue:"#fec382"},
{name:"Apricot Blush",
hexvalue:"#feaea5"},
{name:"Apricot Brandy",
hexvalue:"#c26a5a"},
{name:"Apricot Brown",
hexvalue:"#cc7e5b"},
{name:"Apricot Buff",
hexvalue:"#cd7e4d"},
{name:"Apricot Chicken",
hexvalue:"#da8923"},
{name:"Apricot Cream",
hexvalue:"#f1bd89"},
{name:"Apricot Flower",
hexvalue:"#ffbb80"},
{name:"Apricot Foam",
hexvalue:"#eeded8"},
{name:"Apricot Fool",
hexvalue:"#ffd2a0"},
{name:"Apricot Freeze",
hexvalue:"#f3cfb7"},
{name:"Apricot Gelato",
hexvalue:"#f5d7af"},
{name:"Apricot Glazed Chicken",
hexvalue:"#eeaa22"},
{name:"Apricot Glow",
hexvalue:"#ffce79"},
{name:"Apricot Ice",
hexvalue:"#fff6e9"},
{name:"Apricot Ice Cream",
hexvalue:"#f8cc9c"},
{name:"Apricot Iced Tea",
hexvalue:"#fbbe99"},
{name:"Apricot Illusion",
hexvalue:"#e2c4a6"},
{name:"Apricot Jam",
hexvalue:"#eea771"},
{name:"Apricot Light",
hexvalue:"#ffca95"},
{name:"Apricot Lily",
hexvalue:"#fecfb5"},
{name:"Apricot Mix",
hexvalue:"#b47756"},
{name:"Apricot Mousse",
hexvalue:"#fcdfaf"},
{name:"Apricot Nectar",
hexvalue:"#ecaa79"},
{name:"Apricot Obsession",
hexvalue:"#f8c4b4"},
{name:"Apricot Orange",
hexvalue:"#c86b3c"},
{name:"Apricot Preserves",
hexvalue:"#eeb192"},
{name:"Apricot Red",
hexvalue:"#e8917d"},
{name:"Apricot Sherbet",
hexvalue:"#facd9e"},
{name:"Apricot Sorbet",
hexvalue:"#e8a760"},
{name:"Apricot Spring",
hexvalue:"#f1b393"},
{name:"Apricot Tan",
hexvalue:"#dd9760"},
{name:"Apricot Wash",
hexvalue:"#fbac82"},
{name:"Apricot White",
hexvalue:"#f7f0db"},
{name:"Apricot Yellow",
hexvalue:"#f7bd81"},
{name:"Apricotta",
hexvalue:"#d8a48f"},
{name:"April Blush",
hexvalue:"#f6d0d8"},
{name:"April Fool's Red",
hexvalue:"#1fb57a"},
{name:"April Green",
hexvalue:"#a9b062"},
{name:"April Love",
hexvalue:"#8b3d2f"},
{name:"April Mist",
hexvalue:"#ccd9c9"},
{name:"April Showers",
hexvalue:"#dadeb5"},
{name:"April Sunshine",
hexvalue:"#fbe198"},
{name:"April Tears",
hexvalue:"#b4cbd4"},
{name:"April Wedding",
hexvalue:"#c5cfb1"},
{name:"April Winds",
hexvalue:"#d5e2e5"},
{name:"Aqua",
hexvalue:"#00ffff"},
{name:"Aqua Bay",
hexvalue:"#b5dfc9"},
{name:"Aqua Belt",
hexvalue:"#7acad0"},
{name:"Aqua Bloom",
hexvalue:"#96d3d8"},
{name:"Aqua Blue",
hexvalue:"#79b6bc"},
{name:"Aqua Breeze",
hexvalue:"#d8e8e4"},
{name:"Aqua Clear",
hexvalue:"#8bd0dd"},
{name:"Aqua Cyan",
hexvalue:"#01f1f1"},
{name:"Aqua Deep",
hexvalue:"#014b43"},
{name:"Aqua Eden",
hexvalue:"#85c7a6"},
{name:"Aqua Experience",
hexvalue:"#038e85"},
{name:"Aqua Fiesta",
hexvalue:"#8cc3c3"},
{name:"Aqua Foam",
hexvalue:"#adc3b4"},
{name:"Aqua Forest",
hexvalue:"#5fa777"},
{name:"Aqua Fresco",
hexvalue:"#4a9fa3"},
{name:"Aqua Frost",
hexvalue:"#a9d1d7"},
{name:"Aqua Glass",
hexvalue:"#d2e8e0"},
{name:"Aqua Green",
hexvalue:"#12e193"},
{name:"Aqua Grey",
hexvalue:"#889fa5"},
{name:"Aqua Haze",
hexvalue:"#d9ddd5"},
{name:"Aqua Island",
hexvalue:"#a1dad7"},
{name:"Aqua Lake",
hexvalue:"#30949d"},
{name:"Aqua Mist",
hexvalue:"#a0c9cb"},
{name:"Aqua Nation",
hexvalue:"#08787f"},
{name:"Aqua Oasis",
hexvalue:"#bce8dd"},
{name:"Aqua Obscura",
hexvalue:"#05696b"},
{name:"Aqua Pura",
hexvalue:"#ddf2ee"},
{name:"Aqua Rapids",
hexvalue:"#63a39c"},
{name:"Aqua Revival",
hexvalue:"#539f91"},
{name:"Aqua Sea",
hexvalue:"#6baaae"},
{name:"Aqua Sky",
hexvalue:"#7bc4c4"},
{name:"Aqua Smoke",
hexvalue:"#8c9fa0"},
{name:"Aqua Sparkle",
hexvalue:"#d3e4e6"},
{name:"Aqua Splash",
hexvalue:"#85ced1"},
{name:"Aqua Spray",
hexvalue:"#a5dddb"},
{name:"Aqua Spring",
hexvalue:"#e8f3e8"},
{name:"Aqua Squeeze",
hexvalue:"#dbe4dc"},
{name:"Aqua Tint",
hexvalue:"#e5f1ee"},
{name:"Aqua Velvet",
hexvalue:"#00a29e"},
{name:"Aqua Verde",
hexvalue:"#56b3c3"},
{name:"Aqua Vitale",
hexvalue:"#7bbdc7"},
{name:"Aqua Waters",
hexvalue:"#00937d"},
{name:"Aqua Whisper",
hexvalue:"#bfdfdf"},
{name:"Aqua Wish",
hexvalue:"#a0e3d1"},
{name:"Aqua Zing",
hexvalue:"#7cd8d6"},
{name:"Aqua-Sphere",
hexvalue:"#9cb0b3"},
{name:"Aquacade",
hexvalue:"#e1f0ea"},
{name:"Aquadazzle",
hexvalue:"#006f49"},
{name:"Aquadulce",
hexvalue:"#7b9f82"},
{name:"Aqualogic",
hexvalue:"#57b7c5"},
{name:"Aquamarine",
hexvalue:"#2ee8bb"},
{name:"Aquamarine Blue",
hexvalue:"#71d9e2"},
{name:"Aquamarine Dream",
hexvalue:"#b3c4ba"},
{name:"Aquamarine Ocean",
hexvalue:"#82cdad"},
{name:"Aquamentus Green",
hexvalue:"#00a800"},
{name:"Aquarelle",
hexvalue:"#61aab1"},
{name:"Aquarelle Beige",
hexvalue:"#e8e0d5"},
{name:"Aquarelle Blue",
hexvalue:"#bfe0e4"},
{name:"Aquarelle Green",
hexvalue:"#e2f4e4"},
{name:"Aquarelle Lilac",
hexvalue:"#edc8ff"},
{name:"Aquarelle Mint",
hexvalue:"#dbf4d8"}]